# ----
# Site

title: senseBox
url: "https://docs.sensebox.de/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: images/sensebox_logo.svg
description: senseBox Knowledge Base.
author:
  name: senseBox
  email: info@sensebox.de
  twitter: sensebox_de
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENCE

collections:
  sets:
  descriptions:

jekyll-archives:
  enabled: ["categories"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      type: "sets"
    values:
      _hide_content: true
  - scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
